version: '3.8'

services:
  opencart-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rami/opencart-enterprise:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${HOST_PORT}:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - OC_ADMIN_USER=${OC_ADMIN_USER}
      - OC_ADMIN_PASS=${OC_ADMIN_PASS}
      - OC_ADMIN_DIR=${OC_ADMIN_DIR:-admin}
    volumes:
      - opencart_images:/var/www/html/image              # لحفظ الصور
      - opencart_storage:/var/www/storage                # لحفظ التخزين
      - opencart_extensions:/var/www/html/extension      # لحفظ الثيمات والإضافات
    networks:
      - presta-net

volumes:
  opencart_images:      # للحفاظ على صور المنتجات آمنة ومستقلة حتى لو تم تحديث الكود
  opencart_storage:     # للحفاظ على إضافات المتجر والملفات المؤقتة آمنة ومستقلة
  opencart_extensions:  # للحفاظ على الثيمات والإضافات (Extensions) عند تحديث الكونتينر

networks:
  presta-net:
    external: true      # الشبكة الحالية للربط بقاعدة البيانات المشتركة
